-- Create settings table
CREATE TABLE IF NOT EXISTS settings (
  id TEXT PRIMARY KEY,
  value JSONB NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Create external_links table
CREATE TABLE IF NOT EXISTS external_links (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  slug TEXT UNIQUE NOT NULL,
  url TEXT NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Enable RLS (Optional, but recommended)
-- ALTER TABLE settings ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE external_links ENABLE ROW LEVEL SECURITY;

-- Create basic policies (Allowing all for now as requested for simplicity)
-- CREATE POLICY "Allow public read" ON settings FOR SELECT USING (true);
-- CREATE POLICY "Allow public read" ON external_links FOR SELECT USING (true);

-- Insert default settings
INSERT INTO settings (id, value)
VALUES ('global', '{
  "domainPrice": 9.99,
  "vpsMarkup": 0,
  "whmcsUrl": "https://billing.jannatit.com",
  "whmcsApiUrl": "https://billing.jannatit.com/includes/api.php",
  "checkoutMode": "whmcs",
  "manualRedirectUrl": "https://billing.jannatit.com/cart.php?a=add&pid=1",
  "paymentMethods": [
    {"id": "paypal", "name": "PayPal", "active": true},
    {"id": "stripe", "name": "Credit Card", "active": true},
    {"id": "bkash", "name": "bKash", "active": true}
  ]
}'::jsonb)
ON CONFLICT (id) DO NOTHING;
